import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Copy, Check, Bookmark, Sparkles, User, RefreshCw, FileDown, Share2 } from 'lucide-react';
import { saveAnswer } from '../../services/settingsService';

export default function MessageBubble({ message, userQueryText = '', onRegenerate }) {
  const isUser = message.role === 'user';
  const [copied, setCopied] = useState(false);
  const [bookmarked, setBookmarked] = useState(false);

  const now = new Date();
  const timeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: true }).toUpperCase();

  const handleCopy = () => {
    navigator.clipboard.writeText(message.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleBookmark = async () => {
    if (bookmarked) return;
    try {
      const title = userQueryText.slice(0, 55) || "Saved Answer";
      await saveAnswer(title, "General", message.answer_type || "normal", message.content);
      setBookmarked(true);
      setTimeout(() => setBookmarked(false), 3000);
    } catch (err) {
      console.error("Failed to save answer:", err);
      alert("Failed to bookmark answer: " + (err.response?.data?.detail || err.message));
    }
  };

  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html><head><title>Prepzo AI - Answer</title>
      <style>body{font-family:system-ui,sans-serif;padding:2rem;max-width:800px;margin:0 auto;line-height:1.7}
      h1,h2,h3{margin-top:1.2em}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:8px;text-align:left}
      </style></head><body>
      <h3>${userQueryText || 'Answer'}</h3><hr/>
      ${message.content.replace(/\n/g, '<br/>')}
      <br/><br/><small>Generated by Prepzo AI</small>
      </body></html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  // ===== User message =====
  if (isUser) {
    return (
      <div className="w-full flex justify-end py-[8px]">
        <div className="flex items-start gap-[12px] max-w-[75%] flex-row-reverse">
          <div className="w-[32px] h-[32px] rounded-full bg-[#1E293B] border border-[#334155] flex items-center justify-center shrink-0">
            <User size={14} className="text-[#94A3B8]" />
          </div>
          <div className="flex flex-col items-end gap-[4px]">
            <div className="bg-[#111827] border border-[#1E293B] text-[#E2E8F0] px-[16px] py-[12px] rounded-[16px] rounded-tr-[4px] text-[14px] leading-[22px]">
              <p className="whitespace-pre-wrap">{message.content}</p>
            </div>
            <span className="text-[10px] text-[#4B5563] px-[4px]">{timeStr}</span>
          </div>
        </div>
      </div>
    );
  }

  // ===== AI message =====
  return (
    <div className="w-full flex justify-start py-[8px]">
      <div className="flex items-start gap-[12px] max-w-[85%]">
        <div className="w-[32px] h-[32px] rounded-full bg-[#10B981]/12 border border-[#10B981]/25 flex items-center justify-center shrink-0">
          <Sparkles size={14} className="text-[#10B981]" />
        </div>
        <div className="flex-1 min-w-0">
          {/* AI Label + timestamp — aligned */}
          <div className="flex items-center gap-[8px] mb-[8px]">
            <span className="text-[13px] font-semibold text-[#10B981]">Prepzo AI</span>
            <span className="text-[11px] text-[#64748B]">{timeStr}</span>
          </div>

          {/* Response content */}
          <div className="markdown-container text-[14px] leading-[24px] text-[#E2E8F0]">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {message.content}
            </ReactMarkdown>
          </div>

          {/* Action Row — consistent 36px button height */}
          <div className="flex items-center gap-[4px] pt-[12px] mt-[12px] border-t border-[#1E293B]/50 flex-wrap">
            {[
              { onClick: handleCopy, icon: copied ? Check : Copy, label: copied ? 'Copied' : 'Copy', active: copied },
              ...(onRegenerate ? [{ onClick: onRegenerate, icon: RefreshCw, label: 'Regenerate' }] : []),
              { onClick: handleBookmark, icon: Bookmark, label: bookmarked ? 'Saved' : 'Save', active: bookmarked, fillActive: true },
              { onClick: handleExportPDF, icon: FileDown, label: 'Export PDF' },
              { onClick: () => {}, icon: Share2, label: 'Share' },
            ].map((action, i) => {
              const Icon = action.icon;
              return (
                <button
                  key={i}
                  onClick={action.onClick}
                  className={`h-[32px] flex items-center gap-[6px] px-[10px] rounded-[8px] hover:bg-[#1E293B]/40 transition-colors text-[12px] font-medium cursor-pointer ${
                    action.active ? 'text-[#10B981]' : 'text-[#64748B] hover:text-[#94A3B8]'
                  }`}
                >
                  <Icon size={14} className={action.active && action.fillActive ? 'fill-[#10B981]' : ''} />
                  <span>{action.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
